# Generated by Django 5.2.11 on 2026-04-14 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_indexes_isread'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameIndex(
            model_name='complaint',
            new_name='complaints__user_id_a0c61a_idx',
            old_name='complaint_user_status_idx',
        ),
        migrations.RenameIndex(
            model_name='complaint',
            new_name='complaints__status_7c8de0_idx',
            old_name='complaint_status_idx',
        ),
        migrations.RenameIndex(
            model_name='complaint',
            new_name='complaints__created_a26128_idx',
            old_name='complaint_created_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='complaints__user_id_0f3b56_idx',
            old_name='notif_user_isread_idx',
        ),
        migrations.AlterField(
            model_name='comment',
            name='complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='complaints.complaint'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
